//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wtw
{
    using System;
    using System.Collections.Generic;
    
    public partial class accident
    {
        public long id { get; set; }
        public Nullable<int> Deaths { get; set; }
        public Nullable<int> Injury { get; set; }
        public Nullable<float> Lat { get; set; }
        public Nullable<float> Long { get; set; }
        public string Postcode { get; set; }
        public string status { get; set; }
    }
}
